<?xml version="1.0"?>
<package format="3">
  <name>so101_brain</name>
  <version>0.2.0</version>
  <description>Intelligence of the arm — IK (ikpy) and autonomous pick &amp; place loop.</description>
  <maintainer email="tek5@epitech.eu">Tek5 Robotics</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>so101_interfaces</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>so101_description</exec_depend>
  <exec_depend>pinocchio</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
